name: telescope
description: A simple and easy to use state manager for flutter.
version: 1.0.0
repository: https://github.com/ali77gh/Telescope
homepage: https://github.com/ali77gh/Telescope

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
